# pyright: reportAny=false, reportMissingParameterType=false, reportUnknownArgumentType=false, reportUnknownMemberType=false, reportUnknownVariableType=false, reportReturnType=false

"""mosp → ASS 导出集（决策 43）。

与 export_srt.export_srt_set 同构的 ASS 版：每份文件自带完整 [V4+ Styles]
段（含未使用样式，与 Aegisub 工程一致），只含对应对话行：

- 全量原文：<stem>.ass
- 全量译文：<stem>_<lang>.ass（只含有译文的段；译文与原文同样式）
- 按颜色拆分：<stem>_<颜色>.ass（原文）+ <stem>_<lang>_<颜色>.ass（该色段译文）
  ——无色段归 <stem>_default.ass

样式解析链（决策 43①）：段 `style_ref`（直选）> 顶层 `color_styles[有效颜色]`
> Default。旧工程无 styles/color_styles → 自动注入 Aegisub Default。

段 `overrides` → 行内覆盖标签（Aegisub 标签表顺序）：\\pos/\\fad + 可覆盖的
样式字段（font/字号/四色/粗斜下划线/缩放/字距/旋转/描边/阴影/对齐）。
Style 行专属字段（border_style/边距/encoding/name）无对应 override 标签，
出现在 overrides 里会被忽略——与 ASS 规范一致。

PlayRes = 媒体视频分辨率（ffprobe 探测），失败回落 Aegisub 默认 1280×720。
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from ass_style import default_style, format_style_line, override_color_to_ass
from export_srt import effective_color, load_mosp

# Aegisub 默认新文件分辨率（src/libresrc/default_config.json）
DEFAULT_PLAYRES = (1280, 720)

# 可覆盖字段 → override 标签（值格式化回调）。顺序 = Aegisub 标签表顺序
# （ass_override.cpp 行号序：bord/shad/pos/fad/fscx/fscy/fsp/frz/1c/2c/3c/4c/fn/fs/an/b/i/u/s）。
# 注意标签必须用原始字符串：\b/\f 等是合法转义序列，普通字符串会变成控制字符。
_OVERRIDE_FIELDS = [
    ("outline_w", r"\bord", lambda v: _g(v)),
    ("shadow_w", r"\shad", lambda v: _g(v)),
    ("pos", r"\pos", lambda v: "%d,%d" % (int(v[0]), int(v[1]))),
    ("fade", r"\fad", lambda v: "%d,%d" % (int(v[0]), int(v[1]))),
    ("scale_x", r"\fscx", lambda v: _g(v)),
    ("scale_y", r"\fscy", lambda v: _g(v)),
    ("spacing", r"\fsp", lambda v: _g(v)),
    ("angle", r"\frz", lambda v: _g(v)),
    ("primary", r"\1c", lambda v: _color_override(v)),
    ("secondary", r"\2c", lambda v: _color_override(v)),
    ("outline", r"\3c", lambda v: _color_override(v)),
    ("shadow", r"\4c", lambda v: _color_override(v)),
    ("font", r"\fn", lambda v: str(v)),
    ("font_size", r"\fs", lambda v: _g(v)),
    ("alignment", r"\an", lambda v: "%d" % int(v)),
    ("bold", r"\b", lambda v: "1" if v else "0"),
    ("italic", r"\i", lambda v: "1" if v else "0"),
    ("underline", r"\u", lambda v: "1" if v else "0"),
    ("strikeout", r"\s", lambda v: "1" if v else "0"),
]

_ASS_INFO = """[Script Info]
; Script generated by kirinuki-pipeline (MAW fork, 决策 43)
Title: {title}
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: {playres_x}
PlayResY: {playres_y}
"""

_STYLES_HEADER = """[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
"""

_EVENTS_HEADER = """[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def _g(value) -> str:
    return "%g" % float(value)


def _color_override(value) -> str:
    """样式段颜色（8 位 ABGR）→ 覆盖标签写法（6 位 + 尾部 &，Aegisub 同款）。"""
    return override_color_to_ass(str(value)) or "&H000000&"


def ms_to_ass_tc(ms: int) -> str:
    """毫秒 → ASS 时间码 `H:MM:SS.cc`（厘秒四舍五入）。"""
    total_cs = round(max(0, int(ms)) / 10)
    h, rem = divmod(total_cs, 360_000)
    m, rem = divmod(rem, 6_000)
    s, cs = divmod(rem, 100)
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


def probe_media_resolution(media: str | None) -> tuple[int, int] | None:
    """ffprobe 取视频流分辨率；不可探测返回 None（调用方回落默认）。"""
    if not media or not isinstance(media, str):
        return None
    path = Path(media)
    if not path.is_file():
        return None
    ffprobe = shutil.which("ffprobe")
    if not ffprobe:
        return None
    try:
        result = subprocess.run(
            [ffprobe, "-v", "error", "-select_streams", "v:0",
             "-show_entries", "stream=width,height", "-of", "csv=p=0", str(path)],
            capture_output=True, text=True, timeout=15, check=False,
        )
        width, height = (part.strip() for part in result.stdout.strip().split(",", 1))
        return (int(width), int(height)) if int(width) > 0 and int(height) > 0 else None
    except (OSError, ValueError, subprocess.SubprocessError):
        return None


def project_styles(project: dict) -> list[dict]:
    """工程样式列表；缺 Default 时自动补入 Aegisub Default（旧工程无感迁移）。"""
    styles = [s for s in project.get("styles") or []
              if isinstance(s, dict) and s.get("name")]
    if not any(s.get("name") == "Default" for s in styles):
        styles.insert(0, default_style())
    return styles


def project_color_styles(project: dict) -> dict[str, str]:
    """顶层 color_styles 清洗：只留非空字符串映射（决策 43①）。"""
    return {str(k): str(v).strip() for k, v in (project.get("color_styles") or {}).items()
            if isinstance(v, str) and v.strip()}


def resolve_style_name(segment: dict, segments: list[dict],
                       style_names: set[str], color_styles: dict[str, str]) -> str:
    """段样式解析链：style_ref（直选）> color_styles[有效颜色] > Default。"""
    ref = segment.get("style_ref")
    if isinstance(ref, str) and ref.strip() in style_names:
        return ref.strip()
    color = effective_color(segment, segments)
    if color and color_styles.get(color) in style_names:
        return color_styles[color]
    return "Default"


def segment_overrides_text(overrides: dict) -> str:
    r"""段 overrides → `{\pos(...)\fad(...)\fs...}` 标签块；无有效字段返回 ""。"""
    parts = []
    for field, tag, fmt in _OVERRIDE_FIELDS:
        if field not in overrides:
            continue
        value = overrides[field]
        try:
            if field == "pos":
                if not (isinstance(value, (list, tuple)) and len(value) == 2):
                    continue
                parts.append(tag + "(" + fmt(value) + ")")
            elif field == "fade":
                if not (isinstance(value, (list, tuple)) and len(value) == 2):
                    continue
                parts.append(tag + "(" + fmt(value) + ")")
            else:
                parts.append(tag + fmt(value))
        except (TypeError, ValueError, IndexError):
            continue  # 覆盖字段损坏 → 忽略该标签，不炸整段（容错）
    return "{" + "".join(parts) + "}" if parts else ""


def ass_text_of(text: str) -> str:
    r"""mosp 文本 → ASS 对话文本：换行 \n → \\N，去掉首尾空白。"""
    return text.replace("\r\n", "\n").replace("\n", "\\N").strip()


def render_ass(entries: list[dict], styles: list[dict], *,
               title: str = "subs", playres: tuple[int, int] = DEFAULT_PLAYRES) -> str:
    """渲染一份 .ass 文本。entries = [{start, end, text, style_name, overrides}]。"""
    parts = [_ASS_INFO.format(title=title, playres_x=playres[0], playres_y=playres[1]),
             _STYLES_HEADER]
    parts += [format_style_line(s) + "\n" for s in styles]
    parts += ["\n", _EVENTS_HEADER]
    for e in entries:
        overrides = segment_overrides_text(e.get("overrides") or {})
        parts.append(
            "Dialogue: 0,%s,%s,%s,,0,0,0,,%s%s\n"
            % (ms_to_ass_tc(e["start"]), ms_to_ass_tc(e["end"]),
               e["style_name"], overrides, ass_text_of(e["text"]))
        )
    return "".join(parts)


def _write_ass(path: Path, entries: list[dict], styles: list[dict],
               *, title: str, playres: tuple[int, int]) -> Path | None:
    if not entries:
        return None
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_ass(entries, styles, title=title, playres=playres),
                    encoding="utf-8")
    return path


def export_ass_set(project: dict, out_dir: Path, *,
                   base_name: str = "subs",
                   colors: list[str] | None = None,
                   media: str | None = None) -> list[Path]:
    """导出整组 ASS 到 out_dir，返回实际写入的文件列表。

    语义对齐 export_srt_set：colors=None = 全部已用颜色（含 default 桶）；
    [] = 不产生颜色文件；全量原文/译文始终导出。media 为 None 时用
    project["media"] 探测 PlayRes。
    """
    segments = project.get("segments") or []
    styles = project_styles(project)
    color_styles = project_color_styles(project)
    style_names = {str(s["name"]) for s in styles}
    lang = (project.get("translation_language") or "").strip()
    has_translation = any(
        isinstance(s, dict) and s.get("translation", "").strip() for s in segments
    )
    playres = probe_media_resolution(media or project.get("media")) or DEFAULT_PLAYRES

    def make_entry(segment: dict, text: str) -> dict:
        return {
            "start": int(segment["start"]), "end": int(segment["end"]),
            "text": text,
            "style_name": resolve_style_name(segment, segments, style_names, color_styles),
            "overrides": (segment.get("overrides")
                          if isinstance(segment.get("overrides"), dict) else {}),
        }

    written: list[Path] = []

    # 全量原文
    original = [make_entry(s, s["text"]) for s in segments
                if isinstance(s, dict) and s.get("text", "").strip()]
    if (p := _write_ass(out_dir / f"{base_name}.ass", original, styles,
                        title=base_name, playres=playres)):
        written.append(p)

    # 全量译文（只含有译文的段）
    if has_translation:
        translated = [make_entry(s, s["translation"]) for s in segments
                      if isinstance(s, dict) and s.get("translation", "").strip()]
        if (p := _write_ass(out_dir / f"{base_name}_{lang}.ass", translated, styles,
                            title=f"{base_name}_{lang}", playres=playres)):
            written.append(p)

    # 按颜色拆分（colors=None → 全部已用颜色）
    buckets: dict[str, list[dict]] = {}
    bucket_translations: dict[str, list[dict]] = {}
    for s in segments:
        if not isinstance(s, dict) or not s.get("text", "").strip():
            continue
        color = effective_color(s, segments) or "default"
        buckets.setdefault(color, []).append(make_entry(s, s["text"]))
        if has_translation and s.get("translation", "").strip():
            bucket_translations.setdefault(color, []).append(make_entry(s, s["translation"]))
    if colors is None:
        colors = sorted(buckets.keys())
    for color in colors:
        if color not in buckets:
            continue
        if (p := _write_ass(out_dir / f"{base_name}_{color}.ass", buckets[color], styles,
                            title=f"{base_name}_{color}", playres=playres)):
            written.append(p)
        if color in bucket_translations and (
                p := _write_ass(out_dir / f"{base_name}_{lang}_{color}.ass",
                                bucket_translations[color], styles,
                                title=f"{base_name}_{lang}_{color}", playres=playres)):
            written.append(p)
    return written


def load_project(path: Path) -> dict:
    """读取 mosp 工程（与 export_srt.load_mosp 同义，统一入口便于测试）。"""
    return load_mosp(path)
